### ISSUE TITLE
Remaining issues preventing Brotli.NET from loading on Linux

### ISSUE THREAD

**Issue by coolymike** [Yellow-Dog-Man/brotli.net#3]
Currently, Brotli.NET does not work on Linux, causing in-game cloud syncing to be entirely broken. There are 2 issues preventing it from loading:
1. https://github.com/dotnet/runtime/issues/15112, which causes the Linux native build to attempt loading brolib_x64.dll (a Windows-native DLL).
2. The paths Brotli.NET attempts searching under Linux does not include the `Resonite/Resonite_Data/Plugins` directory, where `brolib_x64.so` is stored.

Once these two issues are resolved, Brotli.NET (and in turn, Brotli) function on Linux as expected. This allows for syncing records on the Linux native build of Resonite.

# Issue 1
This is caused by `RuntimeInformation.IsOSPlatform`, which returns results for the compile target, and not the current runtime. According to the issue I linked above, this is intended behavior of the library. I verified this behavior by logging the output of that library against the output of #1 (on the Linux native build)
```
=============================
RuntimeInformation.IsOSPlatform says:
Windows: True
Linux: False

Custom implementation says:
Windows: False
Linux: True
=============================
```
This issue can be fixed either:
- By replacing the call to `RuntimeInformation.IsOSPlatform` with a custom implementation like #1. The implementation that FrooxEngine itself uses to determine the platform could possibly be used here too, as it works and is well tested.
- Or by replacing the `System.Runtime.InteropServices.RuntimeInformation.dll` included with the Linux build of Resonite to have a Linux compile target. This would allow the `RuntimeInformation.IsOSPlatform` function to return the proper values for Linux. (I have not explicitly tested this solution)

# Issue 2
Brotli.NET is a .NET wrapper for the native Brotli library. Resonite includes this library for both Windows and Linux under `Resonite/Resonite_Data/Managed/brolib_x64.dll` for Windows and `Resonite/Resonite_Data/Plugins/brolib_x64.so` for Linux. The path for the `Plugins` directory is not used to search for the Brotli native library, as such Brotli.NET fails to find the library on Linux.

The paths Brotli.NET uses on Linux to find the native Brotli library include:
```
Resonite/Resonite_Data/Managed
Resonite/Resonite_Data/Managed/runtimes/linux/native
runtimes/linux/native
Resonite/Resonite_Data/Managed/../../runtimes/linux/native
Resonitebin/runtimes/linux/native
Resonite/Resonite_Data/Managed/runtimes/linux/native
```
These paths are almost the same as on Windows, except on Windows, `win` is used instead of `linux`.

This issue can be fixed either:
- By simply moving the `brolib_x64.so` to `Resonite/Resonite_Data/Managed`, where `brolib_x64.dll` is also located.
- Or by adding the `Plugins` directory to the output of the `GetPossibleRuntimeDirectories` function.

**Comment by ProbablePrime** [comment]
Thanks for the detailed research.

I'll resolve this when I can.

**Comment by coolymike** [comment]
After having used the workaround for a while, I have run into an issue with the Dash resetting when modified and synced on the Linux native build. I am unsure what causes this, and it most likely will need a different issue on the main repo.

**Comment by coolymike** [comment]
I noticed this issue is on the [Community Help Welcome](https://github.com/orgs/Yellow-Dog-Man/projects/30/views/1) board with the description: "Ci needs to be updated to build linux correctly". This is an incorrect summary of the current state of this issue.

Issue 1 in the original post is only solved by either changing code in Brotli.NET (which was rejected in #1), or building `System.Runtime.InteropServices.RuntimeInformation.dll` specifically with the Linux compile target. That library is (as far as I'm aware) not currently handled with CI. The same issue (IsOSPlatform returning compile target information) is the cause of several other issues on Linux, including PDFiumSharp not working on Linux.

Issue 2 in the original post is best solved by moving the `brolib_x64.so` file to a different directory like `Resonite_Data/Managed`. The target directory for this file is not defined by CI.

As such, there is currently nothing the community can do for this issue. It is entirely up to YDMS to solve this.

**Comment by ProbablePrime** [comment]
Some of those descriptions are out of date, this is entirely on me yea.

**Comment by ProbablePrime** [comment]
Looking into this more, the native library loading is insanely complex. Stuff like: https://github.com/Yellow-Dog-Man/brotli.net/blob/master/Brotli.NET/Brotli.Core/Interop/NativeMethods.cs and https://github.com/Yellow-Dog-Man/brotli.net/blob/master/Brotli.NET/Brotli.Core/Interop/NativeLibraryLoader.cs

Just aren't usually required anymore.

https://learn.microsoft.com/en-us/dotnet/standard/native-interop/native-library-loading is the current guidance for native library loading.

I plan to investigate updating this entire repository to the new handling, but need to double check the compatibility with the .net versions offered by this repo and with the native libraries and how we talk to them.

On the surface this seems kinda "simple" as in to update to that documentation i linked, but something made the original author use the more complex loader so I'll figure out what.

**Comment by ProbablePrime** [comment]
Actually Cyro partially fixed this awhile back when they resolved some of our native library location woes. You can now see the actual problem on Linux is:
```
System.TypeInitializationException: The type initializer for 'Brotli.Brolib64' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library '__Internal' or one of its dependencies. In order to h>/home/container/Headless/runtimes/linux-x64/native/__Internal.so: cannot open shared object file: No such file or direc>/home/container/Headless/runtimes/linux/native/__Internal.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/__Internal.so: cannot open shared object file: No such file or dir>/home/container/Headless/__Internal.so: cannot open shared object file: No such file or directory
```

Which is from here: https://github.com/Yellow-Dog-Man/brotli.net/blob/master/Brotli.NET/Brotli.Core/Interop/NativeMethods.cs#L21-L34

The use of __Internal is strange, most references I can find to it appear to be referring to Mono. The Strongest thing I can find is this: https://dev.to/jeikabu/loading-native-libraries-in-c-fh6 which is a great resource on the general problem. 

I've been experiencing a native library loading issue every 1-3 months for a [long time](https://github.com/Yellow-Dog-Man/Msdfgen.NET/commit/ba0f2240d14495792bf7197c3cc96a03a2c7f543))

I should probably write a blog at this point. Anyway, looking into their library, these calls: https://github.com/zplus/csnng/blob/master/src/csnng.NetStandard/Interop.cs#L115-L122

Should map to the use of __Internal here: https://github.com/Yellow-Dog-Man/brotli.net/blob/master/Brotli.NET/Brotli.Core/Interop/NativeMethods.cs#L21-L34

Which should fix us up. 

As is tradition with my attempt to fix all this stuff, I'll see if I can get Unit Tests + GH Workflows to prove successful library loading on all of our target platforms.

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14238672208 first test run!

**Comment by ProbablePrime** [comment]
Ok some hours later we're now running Verify, Verify is awesome for this kinda thing.

By following all of their docs we now have the failing Linux test uploading its failures: https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14240994128/job/39910647829 

With these we can download them and compare them locally to figure out the problem. That's much better than the previous run: https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14240453645/job/39908957030 where I outputted 110KB as a numeric array to string >.<

**Comment by ProbablePrime** [comment]
im actually going to just update the native library version files first though as it occurs to me that I have no idea how old they are.

**Comment by ProbablePrime** [comment]
Realized there wasn't an easier to read non-technical update, so here's one:
- The native library is now loading correctly on Linux
- However, the Tests fail on Linux, They do not output the same bytes as on Windows where the compressed files originated.

**Comment by coolymike** [comment]
> no idea how old they are

I can actually comment on that one, they're directly from upstream: https://github.com/XieJJ99/brotli.net/tree/master/Brotli.NET/Brotli.Core/runtimes/linux/native

That's 4 years old, v1.0.9, compiled by a random internet user. Not a security risk at all.

[Brotli itself](https://github.com/google/brotli) is at v1.1.0, though updating is not a single click. Brotli.net expects a statically compiled version of brotli common, decoder, and encoder in one shared object, which is no longer a compile target of upstream brotli.

Headless on ARM community projects have been able to accomplish this iirc by patching CMakeLists.txt and using gcc to compile one static library:
<details>
  <summary>CMakeLists.txt patch</summary>
<pre><code>diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7389560..d734488 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -106,6 +106,15 @@ if(BROTLI_EMSCRIPTEN)
   set(BUILD_SHARED_LIBS OFF)
 endif()
 
+set(BROTLI_COMMON_C c/common/constants.c c/common/context.c c/common/dictionary.c c/common/platform.c c/common/transform.c)
+set(BROTLI_DEC_C c/dec/bit_reader.c c/dec/decode.c c/dec/huffman.c c/dec/state.c)
+set(BROTLI_ENC_C c/enc/backward_references.c c/enc/backward_references_hq.c c/enc/bit_cost.c c/enc/block_splitter.c c/enc/brotli_bit_stream.c c/enc/cluster.c c/enc/command.c c/enc/compound_dictionary.c c/enc/compress_fragment.c c/enc/compress_fragment_two_pass.c c/enc/dictionary_hash.c c/enc/encode.c c/enc/encoder_dict.c c/enc/entropy_encode.c c/enc/fast_log.c c/enc/histogram.c c/enc/literal_cost.c c/enc/memory.c c/enc/metablock.c c/enc/static_dict.c c/enc/utf8_util.c)
+
+set(BROTLI_STATIC_LIBS brotlicommon-static brotlidec-static brotlienc-static)
+add_library(brotlicommon-static STATIC ${BROTLI_COMMON_C})
+add_library(brotlidec-static STATIC ${BROTLI_DEC_C})
+add_library(brotlienc-static STATIC ${BROTLI_ENC_C})
+
 file(GLOB_RECURSE BROTLI_COMMON_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} c/common/*.c)
 add_library(brotlicommon ${BROTLI_COMMON_SOURCES})
 
@@ -126,7 +135,7 @@ if(BUILD_SHARED_LIBS)
   endforeach()
 endif()
 
-foreach(lib ${BROTLI_LIBRARIES_CORE})
+foreach(lib ${BROTLI_LIBRARIES_CORE} ${BROTLI_STATIC_LIBS})
   target_link_libraries(${lib} ${LIBM_LIBRARY})
   set_property(TARGET ${lib} APPEND PROPERTY INCLUDE_DIRECTORIES ${BROTLI_INCLUDE_DIRS})
   set_target_properties(${lib} PROPERTIES
</pre></code>
<code>gcc -shared -o brolib_x64.so -Wl,--whole-archive libbrotlicommon-static.a libbrotlienc-static.a libbrotlidec-static.a -Wl,--no-whole-archive</code>
</details>

**Comment by ProbablePrime** [comment]
Nice, I'll see what I can do.

**Comment by ProbablePrime** [comment]
I have some CMake changes, I'll be experimenting with tomorrow. I just realized the time though lol.

**Comment by ProbablePrime** [comment]
You can see those Cmake changes here: https://github.com/Yellow-Dog-Man/brotli/commit/251e4b2464b258a9aacff87ba74cc257f174d44c

and the beginnings of a build that tried to use them here: https://github.com/Yellow-Dog-Man/brotli.net/commit/bd83bb397f1a50a4cd26d2b429f300c3922b1726

Im halting using GH actions while i work on this now as the entire toolchain is on a linux machine of mine.

**Comment by ProbablePrime** [comment]
The new Shared Library from: https://github.com/Yellow-Dog-Man/brotli/commit/251e4b2464b258a9aacff87ba74cc257f174d44c

Works and has everything we need, but the tests are still failing. This still means we have some sort of operating system dependent issue on Linux.

I now plan to take the test files from the main Brotli repo: https://github.com/Yellow-Dog-Man/brotli/tree/master/tests/testdata

and to run them through on the .NET side.

That might shake something loose.

**Comment by ProbablePrime** [comment]
You can see those files now running here: https://github.com/Yellow-Dog-Man/brotli.net/commit/c624f9954f6792b684d55e87b119903ef73003f1#diff-15b8499b1e1555007c1d9e60ab8491c076b876e8f14d55164dc96384c68d970f

We do not have the window settings that were used to create these, so I will hunt those down.

**Comment by ProbablePrime** [comment]
They use the default options: https://github.com/Yellow-Dog-Man/brotli/blob/master/c/tools/brotli.md#options

So using those should work!

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/brotli/blob/master/c/tools/brotli.c#L1467 default quality is 11. so 11, 24 for the .net code!

**Comment by ProbablePrime** [comment]
This is fascinating: https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14261609532/job/39974283212

The compressed outputs aren't stable for some very specific cases. So now I need to:
1. Look into the failing windows artifacts, those should be fine :S 
2. Look into the failing linux artifacts to see if there's some reason for OS differences. The failing file is some crazy utf format.

I'm very tempted to just nix those failing files though as 52/54 files being identical on windows and linux is fantastic and convinces me we'll be fine in actual Resonite land.

**Comment by ProbablePrime** [comment]
I forgot that I did not update the windows native library to 1.1.0 its on 1.0.9: https://github.com/Yellow-Dog-Man/brotli.net/tree/master/Brotli.NET/Brotli.Core/runtimes/win/native

That could be the differences, https://github.com/Yellow-Dog-Man/brotli/pull/1 from J4 will help with that so ill do that next.

**Comment by ProbablePrime** [comment]
I had a fun day.
On my original brotli.net branch to fix linux, i got frustrated at the complex custom native loader that this library has. We were having issues and it wasn't working so I ripped it out. But then using the standard .net loader also did not work.

Looking around for.... hours.... it turns out that there were some native issues, that you can read about in: https://github.com/Yellow-Dog-Man/brotli/pull/3 It just messes with some configuration, to output a slightly different dll. 

The original library offered a 64 bit version which i updated and  a 32 bit version which I haven't touched. We don't use 32bit at Resonite and our steam page requires 64 bit. If I can get 64 bit working, then I'll look into 32 but this reduces complexity for now \o/

As a part of that we're now on #5 because #4 has the old native library loader ripped out and isn't working. I may try replacing it again but wanted to reduce scope. If we can get it working with the crunchy loader we will.

Additionally I added some more tests to ensure that the expected brotli version is loaded in our CI. This test is designed to verify that all our target os'es have a valid and identical version: https://github.com/Yellow-Dog-Man/brotli.net/blob/prime/fix/linux-2/Brotli.NET/Brotli.NET.Tests/NativeLibraryLoading.cs#L19

So with that and as you can see from: https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14378732438

We're now up and running on both operating systems using the same version of the library. This is cool.

What isn't cool is that some tests are still failing as they don't meet the expected values

**Comment by ProbablePrime** [comment]
I hex compared one of the failing files:

![Image](https://github.com/user-attachments/assets/8fd4075f-90fb-4787-99a0-a4f7098d80af)

That the binary data is similar with sporadic matching bits(probably some sort of control bits, i dont know Brotli well).

But interestingly the files are different lengths. For clarity:
- Left: Test Compression on my Development Machine on windows
- Right: Test Compression on the Cloud Based GH Action runner.

There is a 7 byte difference in the data stream too.

Looking into Brotli more, there are more parameters we can set: https://www.brotli.org/encode.html#a9a8. 

So what I want to do is to statically set all of these for the tests as some rely on each other and may differ based on OS.

**Comment by ProbablePrime** [comment]
Looking at some statically decompressed files: 

![Image](https://github.com/user-attachments/assets/de344c45-a619-40f9-91e8-ec9c373afe3c)

The differences here are line endings. 

0d0a => CRLF
0a => LF
(https://www.ascii-code.com/)

This makes sense sorta, when it comes to windows vs linux, but im still confused:
1. Is the compression altering line endings?
2. Is the Test Library/Harness Code altering line endings?
3. Is the operating system altering line endings.

Luckily I can just make another test in this mess to figure that out.

However, still debating giving up here, the library works on both operating systems, it just seems to disagree with what's going on.

**Comment by ProbablePrime** [comment]
My fancy newline tests just all failed: https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14461900153/job/40555931695

We're onto something!

**Comment by ProbablePrime** [comment]
https://github.com/VerifyTests/Verify/issues?q=is%3Aissue%20state%3Aclosed%20line%20endings YUP

**Comment by ProbablePrime** [comment]
This was worth it!

Now the same tests are failing on windows and linux for some of the files but not the others! https://github.com/Yellow-Dog-Man/brotli.net/actions/runs/14462490195

As the results are now the same for linux and windows that means we're processing them correctly. The new LF/CRLF tests also verify that.

This is kinda cool to get to the bottom of.

**Comment by ProbablePrime** [comment]
Just gotta look into those failing files now. 

First I want to compare both the failing files to each other, if they are identical from the CI it means my machine is at fault.

**Comment by ProbablePrime** [comment]
Files are identical in CI, I have a hunch one moment.

**Comment by ProbablePrime** [comment]
main @ head will now work on linux. We'll run a release of this dependency and then integrate it into Resonite. Should be in an update coming soon.

**Comment by ProbablePrime** [comment]
https://www.nuget.org/packages/YellowDogMan.Brotli.NET/2.1.1-ydm-0.2.0

Supports Linux!
